pipeline:
  - name: WhitespaceTokenizer
  - name: CountVectorsFeaturizer
  - name: DIETClassifier
    entities: []
  - name: EntitySynonymMapper
language: en


policies:
  - name: FallbackPolicy
  - name: AugmentedMemoizationPolicy
