version: '3.0'
services:
  server:
    build: .
    volumes:
      - .:/app
    entrypoint:
      - python
      - app.py
    ports:
      - "8080:8080"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app
      - FLASK_DEBUG=1
    restart: always
