version: '3.0'
services:
  server:
    build: .
    volumes:
      - .:/app
    entrypoint:
      - flask
      - run
      - --host=0.0.0.0
      - --port=8080
    ports:
      - "8080:8080"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app
      - FLASK_DEBUG=1
    restart: always  
