version: '3.0'
services:
  server:
    build: .
    volumes:
      - .:/app
    entrypoint:
      - python
      - app.py
    ports:
      - "8080:8080"
    environment:
      - HOST=0.0.0.0
      - PORT=8080
    restart: always
