version: '3.0'
services:
  web:
    build: .
    volumes:
      - ./models/:/app/models
    entrypoint:
      - python
      - app.py
    ports:
      - "8080:8080"
    environment:
      - HOST=0.0.0.0
      - PORT=8080
      - PROTOCOL=http
      - ACTION_ENDPOINT=http://localhost:8080/webhook
    restart: always
